spring:
  session:
    store-type: redis
    redis:
      flush-mode: on_save
  profiles:
    include: oauth
  redis:
    host: session-redis-001.pxr9ze.0001.apn2.cache.amazonaws.com
    port: 6379
    datasource:
      url: jdbc:mariadb://acme.appleluck.com:3306/appleluck
      username: admin
      password: Soldesk!
      driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#server:
#  port: 8081
#  servlet:
#    context-path: /map
#
logging.level:
  org.hibernate.SQL: debug

server:
  port: 8080
  servlet:
    context-path: /map

