spring:
  redis:
    host: session-redis.pxr9ze.ng.0001.apn2.cache.amazonaws.com
    port: 6379
  session:
    store-type: redis
    redis:
      flush-mode: on_save
  datasource:
    url: jdbc:mariadb://appleluck-db-dev.cooikna6ekad.ap-northeast-2.rds.amazonaws.com:3306/appleluck
    username: admin
    password: Soldesk!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  profiles:
    include: oauth
    active: dev
server:
  port: 8080
  servlet:
    context-path: /map
logging.level:
  org.hibernate.SQL: debug