spring:
  session:
    store-type: redis
    redis:
      flush-mode: on_save
  profiles:
    include: oauth
  redis:
    host: localhost
    port: 6379
    datasource:
      url: jdbc:mariadb://appleluck-db-dev.cooikna6ekad.ap-northeast-2.rds.amazonaws.com:3306/appleluck
      username: admin
      password: Soldesk!
      driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#server:
#  port: 8081
#  servlet:
#    context-path: /map
#
logging.level:
  org.hibernate.SQL: debug

server:
  port: 8080
  servlet:
    context-path: /map

