spring:
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
  #        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  profiles:
    include: oauth
    active: dev
server:
  port: 8081
  servlet:
    context-path: /map